version: '3'

services:
  weaviate:
    image: semitechnologies/weaviate:1.19.6
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - ONEDRIVE_ROOT=/data
      - WEAVIATE_URL=http://weaviate:8080
    volumes:
      - ./backend:/app
      - ${ONEDRIVE_MOUNT}:/data
    depends_on:
      - weaviate

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  weaviate_data: